### FHIR Server Base URL
@baseUrl = http://localhost:8080/fhir/r4

### Get CapabilityStatement (R4)
GET {{baseUrl}}/metadata

### Search for Medications
GET {{baseUrl}}/Medication

### Search for ChargeItemDefinitions
GET {{baseUrl}}/ChargeItemDefinition

### Search for StructureDefinitions
GET {{baseUrl}}/StructureDefinition

### Search for SearchParameters
GET {{baseUrl}}/SearchParameter

### Get a specific medication (replace id)
GET {{baseUrl}}/Medication/1

### Search with parameter - Medications by code
GET {{baseUrl}}/Medication?code=system|code

### Search with limit
GET {{baseUrl}}/Medication?_count=10

### Get FHIR R4B endpoint
GET http://localhost:8080/fhir/r4b/metadata

### Get FHIR R5 endpoint
GET http://localhost:8080/fhir/r5/metadata

### Search for Special Authorities (all)
GET {{baseUrl}}/ChargeItemDefinition?_profile=https://fhir-ig.digital.health.nz/pharmac-schedules/StructureDefinition/pharmac-charge-item-definition-special-authority

### Search for Funding Rules (all)
GET {{baseUrl}}/ChargeItemDefinition?_profile=https://fhir-ig.digital.health.nz/pharmac-schedules/StructureDefinition/pharmac-charge-item-definition-funding-rules

### Search for Pricing Rules (all)
GET {{baseUrl}}/ChargeItemDefinition?_profile=https://fhir-ig.digital.health.nz/pharmac-schedules/StructureDefinition/pharmac-charge-item-definition-pricing-rules

### Search for Medications by name
GET {{baseUrl}}/Medication?name=Leuprorelin

### Search for Medications by brand
GET {{baseUrl}}/Medication?brand=Ricovir

### Search for Medications by category
GET {{baseUrl}}/Medication?category=Special%20Foods

### Search for Resources by last updated date
GET {{baseUrl}}/ChargeItemDefinition?_lastUpdated=ge2025-06-01&_profile=https://fhir-ig.digital.health.nz/pharmac-schedules/StructureDefinition/pharmac-charge-item-definition-special-authority

### Search for Medications updated since a date
GET {{baseUrl}}/Medication?_lastUpdated=ge2025-01-01

